name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer PHP et ses extensions
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, mysqli
          coverage: xdebug

      # Installer les dépendances avec Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Exécuter les tests PHPUnit
      - name: Run tests
        run: vendor/bin/phpunit --coverage-text --colors=never

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ce job ne s'exécute que si les tests réussissent
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USER@$HOST "cd /var/www/laravel-app && git pull origin main && composer install && php artisan migrate"
